<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{

  public function getLastFiveArticles(){
  return $this
  ->createQueryBuilder('a')
  ->order('publication_date ASC')
  ->getQuery()
  ->setMaxResult(5)
  ->getArrayResult();
}
}
