<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

public function findByArticle($article){
  return $this
        ->createQueryBuilder('c')
        ->where('c.id = :article')
        ->setParameter('article', $article->getId())
        ->getQuery()
        ->execute();
}

public function countCommentsByArticleID($articleID){
  return $this
        ->createQueryBuilder('c')
        ->select('count(c.id)')
        ->where('c.article = :article')
        ->setParameter('article', $articleID)
        ->getQuery()
        ->getSingleScalarResult();
}

}
