# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.comments:
        class: AppBundle\Services\Comments
        arguments: [ '@doctrine' ]

    app.article_extension:
        class: AppBundle\Twig\ArticleExtension
        tags:
            - { name: twig.extension }
        arguments: ['@app.comments']
    app.category_extension:
        class: AppBundle\Twig\CategoryExtension
        tags:
            - { name: twig.extension }
        arguments:
          doctrine: "@doctrine"
    app.tag_extension:
        class: AppBundle\Twig\TagExtension
        tags:
            - { name: twig.extension }
        arguments:
          doctrine: "@doctrine"
    twig.extension.intl:
         class: Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }
